### ISSUE TITLE
When clicking on an exercise, a blue highlight color comes up, and will not go away.

### ISSUE THREAD

**Issue by Stokn9x** [KasperNissen1997/TrickedKnowledgeHub#102]
Fix it

![Image](https://user-images.githubusercontent.com/14901784/235844927-ab7fe4e4-f812-43a1-b4c1-c4ecd8f699df.png)

**Comment by adenstore** [comment]
fixed in the 99 may have done a mistake by fixing it there (dumb dumb here)

**Comment by KasperNissen1997** [comment]
Closed as stale since it was solved as part of #99.
