### ISSUE TITLE
Create a formular that can be used when creating an exercise

### ISSUE THREAD

**Issue by capper0074** [KasperNissen1997/TrickedKnowledgeHub#16]
When a teacher is about to create a new exercise in the system, they must follow a specific formular, so that all exercises are standardized in at least a small way. The formular should not be too strict, nor too loose. It's a feeling my dudes 🤌

**Comment by KasperNissen1997** [comment]
Closed as duplicate, seeing as this was done when creating the CreateExerciseView.
