### ISSUE TITLE
When resizing the window horizontally, the right grid with filters gets hidden

### ISSUE THREAD

**Issue by Stokn9x** [KasperNissen1997/TrickedKnowledgeHub#95]
I think there is a hidden background or form, which overlaps onto the filter grid. Investigate this, and fix it.

![Image](https://user-images.githubusercontent.com/26743629/235616288-816f0ac9-aa0f-432b-a412-2c08694a612d.png)

**Comment by KasperNissen1997** [comment]
Closed as stale, since we moved to a new design which rendered this issue obsolete.
